# -----------------------------------------------------------------------------
# This file is part of P-SOCRATES Analyzer (http://www.p-socrates.eu).
#
# (C) Copyright 2016 Instituto Superior de Engenharia do Porto
#
# Author: Vincent Nelis <nelis@isep.ipp.pt>
# 
# P-SOCRATES Analyzer is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# version 2 as published by the Free Software Foundation, 
# (with a special exception described below).
# 
# Linking this code statically or dynamically with other modules is
# making a combined work based on this code.  Thus, the terms and
# conditions of the GNU General Public License cover the whole
# combination.
# 
# As a special exception, the copyright holders of this library give you
# permission to link this code with independent modules to produce an
# executable, regardless of the license terms of these independent
# modules, and to copy and distribute the resulting executable under
# terms of your choice, provided that you also meet, for each linked
# independent module, the terms and conditions of the license of that
# module.  An independent module is a module which is not derived from
# or based on this library.  If you modify this code, you may extend
# this exception to your version of the code, but you are not
# obligated to do so.  If you do not wish to do so, delete this
# exception statement from your version.
# 
# P-SOCRATES Analyzer is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License version 2 for more details.
# 
# You should have received a copy of the GNU General Public License
# version 2 along with P-SOCRATES Analyzer; if not, write to the
# Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA.
# 
# -----------------------------------------------------------------------------

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1594, 895)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logo2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.left_curtain_pic = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_curtain_pic.sizePolicy().hasHeightForWidth())
        self.left_curtain_pic.setSizePolicy(sizePolicy)
        self.left_curtain_pic.setText(_fromUtf8(""))
        self.left_curtain_pic.setPixmap(QtGui.QPixmap(_fromUtf8(":/orange.png")))
        self.left_curtain_pic.setScaledContents(True)
        self.left_curtain_pic.setObjectName(_fromUtf8("left_curtain_pic"))
        self.gridLayout_2.addWidget(self.left_curtain_pic, 0, 0, 2, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_logo_pic = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_logo_pic.sizePolicy().hasHeightForWidth())
        self.label_logo_pic.setSizePolicy(sizePolicy)
        self.label_logo_pic.setMaximumSize(QtCore.QSize(800, 200))
        self.label_logo_pic.setText(_fromUtf8(""))
        self.label_logo_pic.setPixmap(QtGui.QPixmap(_fromUtf8(":/header_psoc.png")))
        self.label_logo_pic.setScaledContents(True)
        self.label_logo_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logo_pic.setObjectName(_fromUtf8("label_logo_pic"))
        self.horizontalLayout.addWidget(self.label_logo_pic)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.mainTabs = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTabs.sizePolicy().hasHeightForWidth())
        self.mainTabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mainTabs.setFont(font)
        self.mainTabs.setStyleSheet(_fromUtf8(""))
        self.mainTabs.setTabPosition(QtGui.QTabWidget.North)
        self.mainTabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.mainTabs.setElideMode(QtCore.Qt.ElideNone)
        self.mainTabs.setMovable(False)
        self.mainTabs.setObjectName(_fromUtf8("mainTabs"))
        self.tabVariables = QtGui.QWidget()
        self.tabVariables.setObjectName(_fromUtf8("tabVariables"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabVariables)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scrollAreaVariables = QtGui.QScrollArea(self.tabVariables)
        self.scrollAreaVariables.setAcceptDrops(True)
        self.scrollAreaVariables.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaVariables.setWidgetResizable(True)
        self.scrollAreaVariables.setObjectName(_fromUtf8("scrollAreaVariables"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1226, 602))
        self.scrollAreaWidgetContents.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollAreaWidgetContents.setAcceptDrops(True)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollAreaVariables.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollAreaVariables, 1, 0, 1, 2)
        self.btnNewVariable = QtGui.QPushButton(self.tabVariables)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewVariable.sizePolicy().hasHeightForWidth())
        self.btnNewVariable.setSizePolicy(sizePolicy)
        self.btnNewVariable.setMinimumSize(QtCore.QSize(200, 40))
        self.btnNewVariable.setMaximumSize(QtCore.QSize(200, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewVariable.setIcon(icon1)
        self.btnNewVariable.setIconSize(QtCore.QSize(27, 27))
        self.btnNewVariable.setObjectName(_fromUtf8("btnNewVariable"))
        self.gridLayout_3.addWidget(self.btnNewVariable, 0, 0, 1, 2)
        self.mainTabs.addTab(self.tabVariables, _fromUtf8(""))
        self.tabCommands = QtGui.QWidget()
        self.tabCommands.setObjectName(_fromUtf8("tabCommands"))
        self.gridLayout = QtGui.QGridLayout(self.tabCommands)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupCommandInformation = QtGui.QGroupBox(self.tabCommands)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupCommandInformation.sizePolicy().hasHeightForWidth())
        self.groupCommandInformation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupCommandInformation.setFont(font)
        self.groupCommandInformation.setAutoFillBackground(False)
        self.groupCommandInformation.setObjectName(_fromUtf8("groupCommandInformation"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupCommandInformation)
        self.gridLayout_7.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout_7.setHorizontalSpacing(18)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labCommandOperation = QtGui.QLabel(self.groupCommandInformation)
        self.labCommandOperation.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labCommandOperation.setFont(font)
        self.labCommandOperation.setObjectName(_fromUtf8("labCommandOperation"))
        self.gridLayout_7.addWidget(self.labCommandOperation, 2, 0, 1, 1)
        self.labCommandDescription = QtGui.QLabel(self.groupCommandInformation)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labCommandDescription.setFont(font)
        self.labCommandDescription.setObjectName(_fromUtf8("labCommandDescription"))
        self.gridLayout_7.addWidget(self.labCommandDescription, 3, 0, 1, 1)
        self.labCommandName = QtGui.QLabel(self.groupCommandInformation)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labCommandName.setFont(font)
        self.labCommandName.setObjectName(_fromUtf8("labCommandName"))
        self.gridLayout_7.addWidget(self.labCommandName, 0, 0, 1, 1)
        self.cbCommandType = QtGui.QComboBox(self.groupCommandInformation)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbCommandType.setFont(font)
        self.cbCommandType.setObjectName(_fromUtf8("cbCommandType"))
        self.cbCommandType.addItem(_fromUtf8(""))
        self.cbCommandType.addItem(_fromUtf8(""))
        self.cbCommandType.addItem(_fromUtf8(""))
        self.cbCommandType.addItem(_fromUtf8(""))
        self.cbCommandType.addItem(_fromUtf8(""))
        self.cbCommandType.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.cbCommandType, 1, 2, 1, 1)
        self.cbCommandOperation = QtGui.QComboBox(self.groupCommandInformation)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cbCommandOperation.setFont(font)
        self.cbCommandOperation.setObjectName(_fromUtf8("cbCommandOperation"))
        self.gridLayout_7.addWidget(self.cbCommandOperation, 2, 2, 1, 1)
        self.txtCommandDescription = QtGui.QTextEdit(self.groupCommandInformation)
        self.txtCommandDescription.setMinimumSize(QtCore.QSize(0, 80))
        self.txtCommandDescription.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtCommandDescription.setFont(font)
        self.txtCommandDescription.setObjectName(_fromUtf8("txtCommandDescription"))
        self.gridLayout_7.addWidget(self.txtCommandDescription, 3, 2, 1, 1)
        self.labCommandType = QtGui.QLabel(self.groupCommandInformation)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labCommandType.setFont(font)
        self.labCommandType.setObjectName(_fromUtf8("labCommandType"))
        self.gridLayout_7.addWidget(self.labCommandType, 1, 0, 1, 1)
        self.txtCommandName = QtGui.QLineEdit(self.groupCommandInformation)
        self.txtCommandName.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtCommandName.setFont(font)
        self.txtCommandName.setReadOnly(False)
        self.txtCommandName.setObjectName(_fromUtf8("txtCommandName"))
        self.gridLayout_7.addWidget(self.txtCommandName, 0, 2, 1, 1)
        self.chkbCommandStop = QtGui.QCheckBox(self.groupCommandInformation)
        self.chkbCommandStop.setCheckable(True)
        self.chkbCommandStop.setChecked(False)
        self.chkbCommandStop.setObjectName(_fromUtf8("chkbCommandStop"))
        self.gridLayout_7.addWidget(self.chkbCommandStop, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.groupCommandInformation, 5, 1, 1, 1)
        self.gbCommandActions = QtGui.QGroupBox(self.tabCommands)
        self.gbCommandActions.setStyleSheet(_fromUtf8("QGroupBox#gbCommandActions { \n"
"     border: 0; \n"
" } "))
        self.gbCommandActions.setTitle(_fromUtf8(""))
        self.gbCommandActions.setObjectName(_fromUtf8("gbCommandActions"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbCommandActions)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnCommandNew = QtGui.QPushButton(self.gbCommandActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCommandNew.sizePolicy().hasHeightForWidth())
        self.btnCommandNew.setSizePolicy(sizePolicy)
        self.btnCommandNew.setMinimumSize(QtCore.QSize(200, 40))
        self.btnCommandNew.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnCommandNew.setFont(font)
        self.btnCommandNew.setIcon(icon1)
        self.btnCommandNew.setIconSize(QtCore.QSize(27, 27))
        self.btnCommandNew.setObjectName(_fromUtf8("btnCommandNew"))
        self.horizontalLayout_2.addWidget(self.btnCommandNew)
        self.btnCommandDelete = QtGui.QPushButton(self.gbCommandActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCommandDelete.sizePolicy().hasHeightForWidth())
        self.btnCommandDelete.setSizePolicy(sizePolicy)
        self.btnCommandDelete.setMinimumSize(QtCore.QSize(200, 40))
        self.btnCommandDelete.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnCommandDelete.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/trash.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCommandDelete.setIcon(icon2)
        self.btnCommandDelete.setIconSize(QtCore.QSize(20, 20))
        self.btnCommandDelete.setObjectName(_fromUtf8("btnCommandDelete"))
        self.horizontalLayout_2.addWidget(self.btnCommandDelete)
        self.gridLayout.addWidget(self.gbCommandActions, 0, 0, 1, 1)
        self.labCommandCodeHeader = QtGui.QLabel(self.tabCommands)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labCommandCodeHeader.setFont(font)
        self.labCommandCodeHeader.setObjectName(_fromUtf8("labCommandCodeHeader"))
        self.gridLayout.addWidget(self.labCommandCodeHeader, 6, 0, 1, 1)
        self.labCommandListHeader = QtGui.QLabel(self.tabCommands)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labCommandListHeader.setFont(font)
        self.labCommandListHeader.setObjectName(_fromUtf8("labCommandListHeader"))
        self.gridLayout.addWidget(self.labCommandListHeader, 1, 0, 1, 1)
        self.lvCommands = QtGui.QListWidget(self.tabCommands)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvCommands.sizePolicy().hasHeightForWidth())
        self.lvCommands.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lvCommands.setFont(font)
        self.lvCommands.setObjectName(_fromUtf8("lvCommands"))
        self.gridLayout.addWidget(self.lvCommands, 5, 0, 1, 1)
        self.labCommandAlertMsg = QtGui.QLabel(self.tabCommands)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labCommandAlertMsg.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labCommandAlertMsg.setFont(font)
        self.labCommandAlertMsg.setText(_fromUtf8(""))
        self.labCommandAlertMsg.setObjectName(_fromUtf8("labCommandAlertMsg"))
        self.gridLayout.addWidget(self.labCommandAlertMsg, 6, 1, 1, 1)
        self.txtCommandCode = QtGui.QPlainTextEdit(self.tabCommands)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtCommandCode.sizePolicy().hasHeightForWidth())
        self.txtCommandCode.setSizePolicy(sizePolicy)
        self.txtCommandCode.setObjectName(_fromUtf8("txtCommandCode"))
        self.gridLayout.addWidget(self.txtCommandCode, 7, 0, 1, 2)
        self.mainTabs.addTab(self.tabCommands, _fromUtf8(""))
        self.tabActions = QtGui.QWidget()
        self.tabActions.setObjectName(_fromUtf8("tabActions"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabActions)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lvActionCommands = QtGui.QListWidget(self.tabActions)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lvActionCommands.setFont(font)
        self.lvActionCommands.setObjectName(_fromUtf8("lvActionCommands"))
        self.gridLayout_5.addWidget(self.lvActionCommands, 2, 2, 1, 1)
        self.labActionListHeader = QtGui.QLabel(self.tabActions)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labActionListHeader.setFont(font)
        self.labActionListHeader.setObjectName(_fromUtf8("labActionListHeader"))
        self.gridLayout_5.addWidget(self.labActionListHeader, 1, 0, 1, 1)
        self.btnNewAction = QtGui.QPushButton(self.tabActions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewAction.sizePolicy().hasHeightForWidth())
        self.btnNewAction.setSizePolicy(sizePolicy)
        self.btnNewAction.setMinimumSize(QtCore.QSize(200, 40))
        self.btnNewAction.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnNewAction.setFont(font)
        self.btnNewAction.setIcon(icon1)
        self.btnNewAction.setIconSize(QtCore.QSize(27, 27))
        self.btnNewAction.setObjectName(_fromUtf8("btnNewAction"))
        self.gridLayout_5.addWidget(self.btnNewAction, 0, 0, 1, 1)
        self.scrollAreaActions = QtGui.QScrollArea(self.tabActions)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.scrollAreaActions.setFont(font)
        self.scrollAreaActions.setWidgetResizable(True)
        self.scrollAreaActions.setObjectName(_fromUtf8("scrollAreaActions"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 616, 581))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.scrollAreaActions.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.addWidget(self.scrollAreaActions, 2, 0, 1, 1)
        self.labActionCommandsHeader = QtGui.QLabel(self.tabActions)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labActionCommandsHeader.setFont(font)
        self.labActionCommandsHeader.setObjectName(_fromUtf8("labActionCommandsHeader"))
        self.gridLayout_5.addWidget(self.labActionCommandsHeader, 1, 2, 1, 1)
        self.mainTabs.addTab(self.tabActions, _fromUtf8(""))
        self.tabConsole = QtGui.QWidget()
        self.tabConsole.setObjectName(_fromUtf8("tabConsole"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabConsole)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.labActionProgress = QtGui.QLabel(self.tabConsole)
        self.labActionProgress.setText(_fromUtf8(""))
        self.labActionProgress.setObjectName(_fromUtf8("labActionProgress"))
        self.verticalLayout.addWidget(self.labActionProgress)
        self.barActionProgress = QtGui.QProgressBar(self.tabConsole)
        self.barActionProgress.setProperty("value", 0)
        self.barActionProgress.setObjectName(_fromUtf8("barActionProgress"))
        self.verticalLayout.addWidget(self.barActionProgress)
        self.txtActionTerminal = QtGui.QTextEdit(self.tabConsole)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtActionTerminal.setFont(font)
        self.txtActionTerminal.setObjectName(_fromUtf8("txtActionTerminal"))
        self.verticalLayout.addWidget(self.txtActionTerminal)
        self.mainTabs.addTab(self.tabConsole, _fromUtf8(""))
        self.tabOptions = QtGui.QWidget()
        self.tabOptions.setEnabled(True)
        self.tabOptions.setObjectName(_fromUtf8("tabOptions"))
        self.formLayout_2 = QtGui.QFormLayout(self.tabOptions)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setRowWrapPolicy(QtGui.QFormLayout.DontWrapRows)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.formLayout_2.setMargin(12)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labOptionRLocation = QtGui.QLabel(self.tabOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labOptionRLocation.sizePolicy().hasHeightForWidth())
        self.labOptionRLocation.setSizePolicy(sizePolicy)
        self.labOptionRLocation.setMinimumSize(QtCore.QSize(0, 25))
        self.labOptionRLocation.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labOptionRLocation.setObjectName(_fromUtf8("labOptionRLocation"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labOptionRLocation)
        self.txtOptionRLocation = QtGui.QLineEdit(self.tabOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtOptionRLocation.sizePolicy().hasHeightForWidth())
        self.txtOptionRLocation.setSizePolicy(sizePolicy)
        self.txtOptionRLocation.setMinimumSize(QtCore.QSize(0, 25))
        self.txtOptionRLocation.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtOptionRLocation.setText(_fromUtf8(""))
        self.txtOptionRLocation.setObjectName(_fromUtf8("txtOptionRLocation"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtOptionRLocation)
        self.labOptionPythonLocation = QtGui.QLabel(self.tabOptions)
        self.labOptionPythonLocation.setObjectName(_fromUtf8("labOptionPythonLocation"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labOptionPythonLocation)
        self.txtOptionPythonLocation = QtGui.QLineEdit(self.tabOptions)
        self.txtOptionPythonLocation.setMinimumSize(QtCore.QSize(0, 25))
        self.txtOptionPythonLocation.setMaximumSize(QtCore.QSize(16777215, 25))
        self.txtOptionPythonLocation.setObjectName(_fromUtf8("txtOptionPythonLocation"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtOptionPythonLocation)
        self.mainTabs.addTab(self.tabOptions, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.mainTabs, 1, 1, 1, 1)
        self.right_curtain_pic = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_curtain_pic.sizePolicy().hasHeightForWidth())
        self.right_curtain_pic.setSizePolicy(sizePolicy)
        self.right_curtain_pic.setText(_fromUtf8(""))
        self.right_curtain_pic.setPixmap(QtGui.QPixmap(_fromUtf8(":/orange.png")))
        self.right_curtain_pic.setScaledContents(True)
        self.right_curtain_pic.setObjectName(_fromUtf8("right_curtain_pic"))
        self.gridLayout_2.addWidget(self.right_curtain_pic, 0, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1594, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpenInterface = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.actionOpenInterface.setFont(font)
        self.actionOpenInterface.setObjectName(_fromUtf8("actionOpenInterface"))
        self.actionSaveInterface = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.actionSaveInterface.setFont(font)
        self.actionSaveInterface.setObjectName(_fromUtf8("actionSaveInterface"))
        self.actionSaveAsInterface = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.actionSaveAsInterface.setFont(font)
        self.actionSaveAsInterface.setObjectName(_fromUtf8("actionSaveAsInterface"))
        self.actionNewInterface = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.actionNewInterface.setFont(font)
        self.actionNewInterface.setObjectName(_fromUtf8("actionNewInterface"))

        self.retranslateUi(MainWindow)
        self.mainTabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtCommandName, self.txtCommandDescription)
        MainWindow.setTabOrder(self.txtCommandDescription, self.lvCommands)
        MainWindow.setTabOrder(self.lvCommands, self.btnNewVariable)
        MainWindow.setTabOrder(self.btnNewVariable, self.scrollAreaVariables)
        MainWindow.setTabOrder(self.scrollAreaVariables, self.btnNewAction)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QuickTrace", None))
        self.btnNewVariable.setText(_translate("MainWindow", "New Variable", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tabVariables), _translate("MainWindow", "Variables", None))
        self.groupCommandInformation.setTitle(_translate("MainWindow", "Information", None))
        self.labCommandOperation.setText(_translate("MainWindow", "Operation", None))
        self.labCommandDescription.setText(_translate("MainWindow", "Description", None))
        self.labCommandName.setText(_translate("MainWindow", "Name", None))
        self.cbCommandType.setItemText(0, _translate("MainWindow", "Shell", None))
        self.cbCommandType.setItemText(1, _translate("MainWindow", "SSH", None))
        self.cbCommandType.setItemText(2, _translate("MainWindow", "SFTP", None))
        self.cbCommandType.setItemText(3, _translate("MainWindow", "R", None))
        self.cbCommandType.setItemText(4, _translate("MainWindow", "Python", None))
        self.cbCommandType.setItemText(5, _translate("MainWindow", "QuickTrace", None))
        self.txtCommandDescription.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.labCommandType.setText(_translate("MainWindow", "Type", None))
        self.chkbCommandStop.setText(_translate("MainWindow", "Stop the current action if this command fails", None))
        self.btnCommandNew.setToolTip(_translate("MainWindow", "Clear all the fields of the form", None))
        self.btnCommandNew.setText(_translate("MainWindow", "New Command", None))
        self.btnCommandDelete.setToolTip(_translate("MainWindow", "Delete the selected command", None))
        self.btnCommandDelete.setText(_translate("MainWindow", "Delete Command", None))
        self.labCommandCodeHeader.setText(_translate("MainWindow", "Command:", None))
        self.labCommandListHeader.setText(_translate("MainWindow", "Select a command to display it", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tabCommands), _translate("MainWindow", "Commands", None))
        self.labActionListHeader.setText(_translate("MainWindow", "List of actions:", None))
        self.btnNewAction.setText(_translate("MainWindow", "New action", None))
        self.labActionCommandsHeader.setText(_translate("MainWindow", "Commands", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tabActions), _translate("MainWindow", "Actions", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tabConsole), _translate("MainWindow", "Console", None))
        self.labOptionRLocation.setText(_translate("MainWindow", "Location of R:", None))
        self.labOptionPythonLocation.setText(_translate("MainWindow", "Location of Python:", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tabOptions), _translate("MainWindow", "Options", None))
        self.actionOpenInterface.setText(_translate("MainWindow", "Open", None))
        self.actionSaveInterface.setText(_translate("MainWindow", "Save", None))
        self.actionSaveAsInterface.setText(_translate("MainWindow", "Save as", None))
        self.actionNewInterface.setText(_translate("MainWindow", "New", None))

import images_rc
