K1_IO_APP_NAME := offload_io
K1_IO_APP_DIR  := libgomp/libgomp-test2
K1_IO_APP_SRCS := ${K1_IO_APP_DIR}/test_io.c

K1_LIBGOMP_PKG2 := libgomp
K1_LIBGOMP_SRCS := $(addprefix ${K1_LIBGOMP_PKG2}, /root.c) \
  $(addprefix ${K1_LIBGOMP_PKG2}, /context.S) \
  $(addprefix ${K1_IO_APP_DIR}, /cluster.c)

K1_ERIKA_APP_SRCS += ${K1_LIBGOMP_SRCS}
K1_ERIKA_APP_DIR  := libgomp/libgomp-test2

K1_ERIKA_APP_INCLUDE_DIRS += ${K1_LIBGOMP_PKG2} $(addprefix ${K1_LIBGOMP_PKG2}, /config/k1)

O := libgomp/libgomp-test2/output

k1-cflags :=  -g3 -DLIBGOMP_MAIN_VERBOSE -DBAR_SIGWAIT -DWORK_FIRST_SCHED -DTASKING_ENABLED -DTASK_BARRIER_BUSY_WAITING #-fopenmp

lflags += -lmppaipc
#${K1_IO_APP_NAME}-lflags += -lmppaipc
